/**
 * Error objects provide additional information about errors encountered while performing an operation. See JSON:API/#error-objects
 */
export type KitsuError = {
  /**
   * a short, human-readable summary of the error. It SHOULD NOT change from occurrence to occurrence
   */
  title: string,

  /**
   * a human-readable explanation for this specific error
   */
  detail: string,

  /**
   * a unique identifier for this error type
   */
  code: string,

  /**
   * a HTTP status code (RFC2616, Section 6) generated by the origin server
   */
  status: string,

  /**
   * an object containing references to the source of the error
   */
  source: {
    /**
     * a JSON Pointer RFC6901 to the associated entity in the request
     */
    pointer: string,

    /**
     * indicates which URI query parameter caused the error
     */
    parameter: string
  }
}

export type KitsuErrorResponse = {
  errors?: KitsuError[];
}
