export * from './anime.service';
import { AnimeService } from './anime.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './characters.service';
import { CharactersService } from './characters.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './manga.service';
import { MangaService } from './manga.service';
export * from './mediaFollows.service';
import { MediaFollowsService } from './mediaFollows.service';
export * from './mediaRelations.service';
import { MediaRelationsService } from './mediaRelations.service';
export * from './posts.service';
import { PostsService } from './posts.service';
export * from './producersStaff.service';
import { ProducersStaffService } from './producersStaff.service';
export * from './reactions.service';
import { ReactionsService } from './reactions.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './siteAnnouncements.service';
import { SiteAnnouncementsService } from './siteAnnouncements.service';
export * from './streamers.service';
import { StreamersService } from './streamers.service';
export * from './userLibraries.service';
import { UserLibrariesService } from './userLibraries.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AnimeService, CategoriesService, CharactersService, CommentsService, GroupsService, MangaService, MediaFollowsService, MediaRelationsService, PostsService, ProducersStaffService, ReactionsService, ReportsService, SiteAnnouncementsService, StreamersService, UserLibrariesService, UsersService];
